### ISSUE TITLE
Add actions with diferent successUrl to AuthController 

### ISSUE THREAD

**Issue by cognitivaxx** [amnah/yii2-user#152] opened 2016-05-24 13:55 UTC
**I would have to login forms, with diferent succesUrl.** So, i was looking into AuthController's action in order to solve this issues... i have added a new action to controller with a diferent succesUrl parameter and set it from the the new login view, but it doesn't work.

This is the action section of my AuthController

class AuthController extends Controller
{
/**
* @inheritdoc
*/
public function actions()
{
return [
'connect' => [
'class' => 'yii\authclient\AuthAction',
'successCallback' => [$this, 'connectCallback'],
'successUrl' => Yii::$app->homeUrl . 'user/account',
],
'login' => [
'class' => 'yii\authclient\AuthAction',
'successCallback' => [$this, 'loginRegisterCallback'],
'successUrl' => $this->getUrl(),
],
'loginadm' => [
'class' => 'yii\authclient\AuthAction',
'successCallback' => [$this, 'loginRegisterCallback'],
'successUrl' => Yii::$app->homeUrl,
],

    ];
}
And this is my social button in a view login:
<?php if (Yii::$app->get("authClientCollection", false)): ?> <div class="col-lg-offset-2"> <?= yii\authclient\widgets\AuthChoice::widget([ 'baseAuthUrl' => ['/user/auth/loginadm'] ]) ?> </div> <?php endif; ?>

In all cases, **the action called is login, but never loginadm, like i wish.**

**Comment by amnah** [comment] 2016-05-25 11:24
duplicate of https://github.com/amnah/yii2-user/issues/151

**Closed by amnah** 2016-05-25 11:24 UTC
